config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :customers, only: %i[index show]
  root to: "customers#index"
  get "customers/alphabetized", to: "customers#alphabetized", as: "alphabetized"
  get "customers/missing_email", to: "customers#missing_email", as: "missing_email"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :notes, presence: true
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:name)
  end

  def missing_email
    @customers = Customer.where(email: [nil, ""])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="column is-one-quarter">
  <div class="card">
    <div class="card-image">
      <% if customer.image.present? %>
        <div class="card-image">
          <figure class="image">
            <%= image_tag customer.image.variant(resize_to_limit: [300, 300]) %>
          </figure>
        </div>
      <% else %>
        <p>IMAGE 📸</p>
      <% end %>
    </div>

    <div class="card-content">
        <div class="media-content">
          <p class="title is-4"><strong><%= customer.name %></strong></p>
          <p>Email: <strong><%= customer.email %></strong></p>
          <p>Phone: <strong><%= customer.phone %></strong></p>
          <br>
          <p><strong><%= customer.notes %></strong></p>
        </div>
    </div>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<div class="columns is-multiline is-mobile">
    <%= render @customers %>
  </div>

app/views/customers/index.html.erb
<%= render partial: 'customer', collection: @customers, locals: {show_link: true} %>

app/views/customers/missing_email.html.erb
<div class="columns is-multiline is-mobile">
    <%= render @customers %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U6CustomerRelationManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
    <h1 class="title is-1"> Movie Characters</h1>
      <p>
        <button class="button is-dark"><%= link_to "Home", root_path, class: "has-text-light" %></button>
        <button class="button is-dark"><%= link_to "Sort by Name", alphabetized_path, class: "has-text-light" %></button>
        <button class="button is-dark"><%= link_to "Missing email", missing_email_path, class: "has-text-light" %></button>
      </p>
      <br>
      <hr>
      <br>
    <%= yield %>
  </body>
</html>